const KEY='life-plan-120-v1';
const PLAN_START='2026-09-01';
const PLAN_DAYS=120;
const categories={
 career:{icon:'↗',name:'Career',target:'6–8 hr / week',intro:'Build one shared foundation for EM, Senior EM, Staff and Principal roles.',fields:[['hours','Hours focused','number'],['applications','Applications sent','number'],['interviews','Interviews / mocks','number']],plan:['System design: scalability, APIs, data, resilience and security','Leadership story bank: build 10 strong STAR stories','Month 1: foundation · Month 2: realistic practice · Month 3: interview mode · Month 4: active pipeline']},
 german:{icon:'ä',name:'German',target:'7 hr / week',intro:'Build a functional A1/A2 base through vocabulary, grammar, listening and speaking.',fields:[['hours','Minutes studied','number'],['speaking','Speaking minutes','number'],['topic','What did you practice?','text']],plan:['20 min vocabulary / spaced repetition','20 min grammar fundamentals','20 min listening and speaking']},
 content:{icon:'▶',name:'Content',target:'7 hr / week',intro:'Create a content engine—not isolated perfect videos.',fields:[['hours','Minutes worked','number'],['stage','Stage','select','Idea,Script,Record,Edit,Publish,Analyze'],['published','Published today','checkbox']],plan:['Move each idea through: Idea → Script → Record → Edit → Publish → Analyze','Use weekdays for individual stages; batch production on weekends','Track what worked after publishing']},
 fitness:{icon:'✦',name:'Fitness',target:'5–6 hr / week',intro:'Lose fat, build strength and improve conditioning without burning out.',fields:[['hours','Minutes trained','number'],['workout','Workout / movement','text'],['steps','Steps','number']],plan:['4 days strength: upper / lower / upper / lower','2 days conditioning: Zone 2, walking, mobility or core','1 day recovery. Consistency beats intensity.']},
 health:{icon:'♡',name:'Health',target:'8 hr sleep · 85% meals',intro:'Sleep is the constraint that protects every other pillar.',fields:[['sleep','Hours slept','number'],['cleanMeals','Clean meals','number'],['totalMeals','Total meals','number'],['energy','Energy (1–5)','number']],plan:['Protect 8 hours of sleep—never sacrifice it for another task','Build meals around protein, vegetables, high-fiber carbs and healthy fats','Aim for 80–90% whole or minimally processed foods']}
};
let selected='dashboard';let data=JSON.parse(localStorage.getItem(KEY)||'{}');
const $=s=>document.querySelector(s); const dateKey=()=>$('#logDate').value;
function save(){localStorage.setItem(KEY,JSON.stringify(data));}
function todayLabel(){const d=new Date($('#logDate').value+'T12:00:00');return d.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'});}
function planDay(){const start=new Date(PLAN_START+'T12:00:00'),selectedDate=new Date(dateKey()+'T12:00:00');return Math.floor((selectedDate-start)/86400000)+1;}
function entry(d=dateKey()){return data[d]||{};}
function categoryScore(key,e=entry()){let v=e[key]||{};if(key==='health')return ((+v.sleep>=8?1:0)+((+v.cleanMeals&&+v.totalMeals&&+v.cleanMeals/+v.totalMeals>=.85)?1:0))/2;if(key==='content')return (+v.hours>=60||v.published?1:0);const targets={career:60,german:60,fitness:45};return +v.hours>=targets[key]?1:0;}
function dailyScore(e=entry()){return Object.keys(categories).reduce((n,k)=>n+categoryScore(k,e),0)/5;}
function mins(key,e=entry()){let v=(e[key]||{});return key==='health'?+v.sleep||0:+v.hours||0;}
function dashboard(){let t=document.querySelector('#dashboardTemplate').content.cloneNode(true);$('#app').replaceChildren(t); let e=entry(),score=Math.round(dailyScore(e)*100);$('#adherence').textContent=score+'%';$('.progress-ring').style.setProperty('--progress',score+'%');let labels={career:'Career',german:'German',content:'Content',fitness:'Fitness',health:'Health'};$('.hero-card .eyebrow').textContent=`DAY ${Math.max(1,planDay())} OF ${PLAN_DAYS} · STARTED SEP 1`;$('#metricGrid').innerHTML=Object.keys(categories).map(k=>{let v=mins(k,e),unit=k==='health'?'hrs sleep':'min today',target=k==='german'||k==='content'?60:k==='career'?60:k==='fitness'?45:8;let pct=Math.min(100,Math.round(v/target*100));return `<article class="metric" data-go="${k}"><div class="metric-top"><span class="metric-icon">${categories[k].icon}</span><span class="goal-chip">${categories[k].target}</span></div><h3>${labels[k]}</h3><div class="metric-value">${v} <small>${unit}</small></div><div class="metric-bar"><i style="width:${pct}%"></i></div></article>`}).join('');document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>render(x.dataset.go));week();}
function week(){let base=new Date($('#logDate').value+'T12:00:00');let day=base.getDay(),sun=new Date(base);sun.setDate(base.getDate()-day);let scores=[];for(let i=0;i<7;i++){let d=new Date(sun);d.setDate(sun.getDate()+i);let key=d.toISOString().slice(0,10);scores.push(Math.round(dailyScore(data[key]||{})*100));}$('#weeklyScore').textContent=Math.round(scores.reduce((a,b)=>a+b,0)/7)+'%';$('#weekBars').innerHTML=scores.map((s,i)=>`<div class="day-bar"><div class="bar-bg"><i style="height:${s}%"></i></div>${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][i]}</div>`).join('');}
function category(key){let c=categories[key],e=entry()[key]||{};$('#app').innerHTML=`<section class="category-head"><div><p class="eyebrow">DAILY LOG</p><h1>${c.icon} ${c.name}</h1><p>${c.intro}</p></div><span class="goal-chip">${c.target}</span></section><section class="log-grid"><div class="entry-card"><h3>Log ${todayLabel()}</h3><form id="logForm"><div class="form-row">${c.fields.map(f=>field(f,e)).join('')}</div><label class="field">Notes<textarea name="notes" placeholder="What felt good? What would help tomorrow?">${e.notes||''}</textarea></label><button class="save">Save daily entry</button><span class="saved-note" id="saved"></span></form></div><aside class="plan-card"><p class="eyebrow">YOUR PLAN</p><h3>Keep it simple</h3><ul class="plan-list">${c.plan.map(x=>`<li>${x}</li>`).join('')}</ul><div class="history"><p class="eyebrow">RECENT ENTRIES</p>${history(key)}</div></aside></section>`;$('#logForm').onsubmit=ev=>{ev.preventDefault();let f=new FormData(ev.target),o={};c.fields.forEach(x=>o[x[0]]=x[2]==='checkbox'?ev.target.elements[x[0]].checked:f.get(x[0]));o.notes=f.get('notes');data[dateKey()]={...entry(),[key]:o};save();$('#saved').textContent='Saved ✓';setTimeout(()=>$('#saved').textContent='',1800);};}
function field(f,e){let [key,label,type,options]=f;if(type==='checkbox')return `<label class="check"><input type="checkbox" name="${key}" ${e[key]?'checked':''}/> ${label}</label>`;if(type==='select')return `<label class="field">${label}<select name="${key}">${options.split(',').map(x=>`<option ${e[key]===x?'selected':''}>${x}</option>`).join('')}</select></label>`;return `<label class="field">${label}<input name="${key}" type="${type}" min="0" value="${e[key]||''}" /></label>`;}
function history(key){let a=Object.entries(data).filter(([,x])=>x[key]).sort((a,b)=>b[0].localeCompare(a[0])).slice(0,4);return a.length?a.map(([d,v])=>`<div class="history-item"><strong>${new Date(d+'T12:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}</strong>${v[key].notes||summary(key,v[key])}</div>`).join(''):'<p class="muted">Your saved entries will appear here.</p>';}
function summary(k,v){return k==='health'?`${v.sleep||0}h sleep · ${v.cleanMeals||0}/${v.totalMeals||0} clean meals`:`${v.hours||0} minutes logged`;}
function weekly(){let rows=Object.keys(categories).map(k=>{let total=0;for(let i=0;i<7;i++){let d=new Date($('#logDate').value+'T12:00');d.setDate(d.getDate()-i);total+=mins(k,data[d.toISOString().slice(0,10)]||{});}return `<div class="review-stat"><b>${total}${k==='health'?'h':'m'}</b><p>${categories[k].name} in the last 7 days</p><div class="mini-bar"><i style="width:${Math.min(100,total/(k==='health'?56:k==='fitness'?300:k==='career'?420:420)*100)}%"></i></div></div>`}).join('');$('#app').innerHTML=`<section class="category-head"><div><p class="eyebrow">SUNDAY CEO DAY</p><h1>Weekly review</h1><p>Look for trends, then set a reasonable next-week target.</p></div></section><section class="review-grid">${rows}</section><section class="entry-card" style="margin-top:18px"><h3>Reflection prompts</h3><ul class="plan-list"><li>What did I learn and practice for my career?</li><li>What did I publish, and what worked?</li><li>What changed in my fitness, sleep and energy?</li><li>What is the one adjustment that will improve next week?</li></ul></section>`;}
function render(view){selected=view;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#viewTitle').textContent=view==='dashboard'?'Your dashboard':view==='weekly'?'Weekly review':categories[view].name;$('#dateLabel').textContent=todayLabel();view==='dashboard'?dashboard():view==='weekly'?weekly():category(view);}
$('#logDate').min=PLAN_START;$('#logDate').value=PLAN_START;$('#logDate').onchange=()=>render(selected);document.querySelectorAll('.nav-item').forEach(x=>x.onclick=()=>render(x.dataset.view));render('dashboard');
